### ISSUE TITLE
결제 도중, 결제결과를 받지 못하면 어떻게 처리를 하나요?

### ISSUE THREAD

**Issue by pcompassion** [iamport/iamport-rest-client-python#2]
javascript 로 iamport 에 결제를 요청하고 redirect_url 로 결과를 받기 전에, 서버에 이상이 있어, 결제 결과를 전달 받지 못하는 경우.

vs

결제 진행중, 결제를 마무리 하지 않고 결제 프로세스를 취소함.

두가지 case 를 어떻게 구별하나요? 
`status == 'paid'` 로 구별하나요?

**Comment by jangbora** [comment]
네 맞습니다. 첫 번째 케이스의 경우 status == 'paid' (true)입니다. 

두 번째 케이스의 경우, status == 'ready' (true)입니다. 
다만, PG사 중 이니시스 웹표준결제창의 경우(이니시스 구형모듈은 해당사항없음) status == 'failed' (true) 이며 fail_reason ('사용자가 결제를 취소함') 이라고 구분됩니다. 
(아임포트 내부적으로도 연구 중인데요, 다른 PG사의 경우에도 사용자가 취소한 경우 status == 'failed'로 처리할 수 있는 방법을 찾으려고 고민 중입니다. 추가로 이런 경우 pending과 같은 신규 status를 만드는 것도 검토하고 있습니다)

때문에, 정확히는 status == 'paid' 또는 status !== 'paid' 로 구분하시는 것이 안전합니다.

**Comment by perhapsspy** [comment]
서버단에서 확인을 한번 더 합니다. 

1. 일단 iamport javascript를 통해 넘어온 응답을 get형태의 url로 서버로 리다이렉트 시킵니다.(데스크탑과 모바일 지원 코드를 일원화 하기 위해 리다이렉트로 처리 했습니다.)
2. 서버단에서 request.GET.get('imp_success') != 'true' 를 확인하면 request.GET.get('error_msg') 를 통해서 사용자가 취소했을때의 메세지를 받아서 출력해줄 수 있습니다.
3. 주문 정보를 별도로 저장하고 있어서 그 정보와 받은 정보를 확인해서 iamport 서버에서 결제 정보를 가져옵니다.
4. 주문 정보와 응답받은 결제 정보를 iampor-rest-client의 is_paid 함수를 호출하면 amount 와 status를 확인해서 결제가 되었는지 알 수 있습니다.

**Comment by pcompassion** [comment]
빠른 답변 감사합니다.
