### ISSUE TITLE
부분 취소 기능이 구현돼 있나요?

### ISSUE THREAD

**Issue by lamiru** [iamport/iamport-rest-client-python#31]
구현돼 있다면 README에 설명이 있으면 좋겠네요.

**Comment by jangbora** [comment]
https://github.com/iamport/iamport-rest-client-python/blob/master/iamport/client.py#L139

kwargs 를 받고 있으므로 iamport.cancel('환불사유', imp_uid='아임포트 거래고유번호', amount=1000) 와 같이 인자 넘기시면 될 것 같습니다.

**Comment by lamiru** [comment]
네, 감사합니다!
