### ISSUE TITLE
메인테이너 구합니다.

### ISSUE THREAD

**Issue by perhapsspy** [iamport/iamport-rest-client-python#33]
이 프로젝트에 제가 충분히 시간을 쓰기 어렵습니다.
추가적인 메인테이너가 이 프로젝트를 관리하는게 좋겠다고 생각합니다.
@jangbora 회사 내부에서 pypi 에 업로드 할 수 있는 계정을 하나 연동해주셔서 관리할 수 있는 상태로 두셔야 할 것 같습니다. 제가 어쩌다 보고 올리려니 거의 2년간 손을 안댄 상태가 되네요.

**Comment by jangbora** [comment]
@perhapsspy 그 동안 수고 많으셨습니다. 많은 도움 받았습니다. 며칠 내로 내부에서 정리하여 다시 댓글 남기겠습니다. 감사합니다.

**Comment by jangbora** [comment]
연락이 한참 늦어버렸습니다. 죄송합니다. pypi 에 iamport 라는 계정을 만들었습니다. 
현재, https://pypi.org/project/iamport-rest-client/ 에 0.8.0 이 본 github과 일치하는 내용으로 보이네요. 이어서 관리하려면 iamport 계정에도 pipy 업로드가 가능하도록 @perhapsspy 님께서 권한을 부여해주시면 되는 걸까요?

**Comment by perhapsspy** [comment]
@jangbora 오너로 추가했습니다.

**Comment by jangbora** [comment]
그동안 많은 도움주셔서 감사합니다.
