### ISSUE TITLE
아임포트 설치시 encoding 에러

### ISSUE THREAD

**Issue by letterflyteam** [iamport/iamport-rest-client-python#6]
안녕하세요.

아래 첨부한 이미지와 같은 환경에서 파이썬을 이용시 pip install iamport-rest-client를 실행하였을때 encoding error가 나게 됩니다. 일단 이 문제에 대해 해결책을 알아보면 좋을꺼 같습니다.

이 문제에 대한 직접적인 솔루션은 아니지만 간접적인 솔루이 있어 함께 공유드립니다. pip install을 사용하지 않고도 github내 iamport/client.py 파일만 불러와서 기업 서비스에 맞게 수정하면 아임포트 서비스를 모두 사용 가능합니다. 따라서 pip install이 encoding문제 뿐만 아니라 다른 여러 문제로 인해 작동을 안하시는 개발자 분들은 위 방법을 이용하시면 신속하게 아임포트 서비스를 이용하실 수 있습니다.

![_modified1](https://cloud.githubusercontent.com/assets/12689435/13905043/9914b60a-eef7-11e5-811f-9580d1203044.png)

![2](https://cloud.githubusercontent.com/assets/12689435/13905046/9f5b2260-eef7-11e5-985f-1627cda98ded.PNG)

**Comment by perhapsspy** [comment]
pip 버전을 업그레이드 해보는건 어떨까요? 한번 확인해볼 수 있을까요?

**Comment by perhapsspy** [comment]
확인해보진 못했지만 readme를 읽어올때 utf-8로 읽게끔 고쳐보았습니다.

**Comment by letterflyteam** [comment]
readme 파일이 문제였고 지금은 설치가 잘 되네요. 예전에 지훈님께도 이 파일이 문제일꺼 같다 말씀은 드렸는데 다행히 해결됬네요.
해결됬다고 issue에도 글 남기겠습니다.

수고하셨습니다.

2016-03-21 14:58 GMT+09:00 Kyoung Up, Jung <notifications@github.com>:

**Comment by perhapsspy** [comment]
해결되었다니 다행입니다. 이슈는 닫겠습니다 :smile:
