### ISSUE TITLE
One time Payment에서 테스트 할 경우

### ISSUE THREAD

**Issue by Beomi** [iamport/iamport-rest-client-python#9]
from iamport import Iamport

# 테스트 용
iamport = Iamport()

으로 할 경우 인자 미전달로 에러가 납니다..

**Comment by perhapsspy** [comment]
테스트 방식이 변경되었는데 README에 반영이 안되어있었습니다. 고쳐놨습니다.
https://github.com/iamport/iamport-rest-client-python/commit/292471bf9ce767e1c1cc5d82f328edc7fac773d0
